server:
  port: 8080

host:
  database: localhost:3306/nexttrucking

spring:
    profiles:
        active: prod

    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: normaluser
      password: Next@123
      url: jdbc:mysql://${host.database}?zeroDateTimeBehavior=convertToNull
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

test:
  yml:
    value: prod
